if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
fi
autoload -Uz compinit && compinit
setopt no_beep

export PATH="/opt/homebrew/bin:$PATH"
export PATH="$HOME/.cargo/env:$PATH"

# Prompt
autoload -Uz vcs_info
setopt prompt_subst
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' stagedstr "%F{magenta}!"
zstyle ':vcs_info:git:*' unstagedstr "%F{yellow}+"
zstyle ':vcs_info:*' formats "%F{cyan}%c%u%b%f"
zstyle ':vcs_info:*' actionformats '%b|%a'
precmd () { vcs_info }
local number_of_jobs="%(1j.%F{208}/%f%F{226}%B%j%b%f.)"
PROMPT='[%B%F{green}%~%f][%F{cyan}$vcs_info_msg_0_%f]%F{yellow}${number_of_jobs}$ %f'

alias gcm='git commit -m'
alias gad='git add .'
alias gps='git push'
alias gpl='git pull'
alias gst='git status'
alias glg='git log --oneline'
alias code="open -a 'Visual Studio Code'"
alias ta='tmux a'

# Docker Desktop
# source /Users/hoge/.docker/init-zsh.sh || true

# Node.js
export NVM_DIR="$HOME/.config/nvm"
lazy_load_nvm() {
  unset -f nvm node npm
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  nvm "$@"
}
node() {
  unset -f nvm node npm
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  node "$@"
}
npm() {
  unset -f nvm node npm
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  npm "$@"
}

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /opt/homebrew/bin/terraform terraform

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/yumaohno/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/yumaohno/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/yumaohno/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/yumaohno/google-cloud-sdk/completion.zsh.inc'; fi
