if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
fi
autoload -Uz compinit && compinit
setopt no_beep

export PATH="/opt/homebrew/bin:$PATH"
export PATH="$HOME/.cargo/env:$PATH"

# Prompt
autoload -Uz vcs_info
setopt prompt_subst
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' stagedstr "%F{magenta}!"
zstyle ':vcs_info:git:*' unstagedstr "%F{yellow}+"
zstyle ':vcs_info:*' formats "%F{cyan}%c%u%b%f"
zstyle ':vcs_info:*' actionformats '%b|%a'
precmd () { vcs_info }
local number_of_jobs="%(1j.%F{208}/%f%F{226}%B%j%b%f.)"
PROMPT='[%B%F{green}%~%f][%F{cyan}$vcs_info_msg_0_%f]%F{yellow}${number_of_jobs}$ %f'

alias gcm='git commit -m'
alias gad='git add .'
alias gps='git push'
alias gpl='git pull'
alias gst='git status'
alias glg='git log --oneline'
alias code="open -a 'Visual Studio Code'"
alias tma='tmux a'
alias tm='tmux'
alias sshga='ssh -p 8022 u0_a310@galaxy-a25-5g'

# Docker Desktop
# source /Users/hoge/.docker/init-zsh.sh || true

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /opt/homebrew/bin/terraform terraform

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/yumaohno/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/yumaohno/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/yumaohno/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/yumaohno/google-cloud-sdk/completion.zsh.inc'; fi

# bun completions
[ -s "/Users/yumaohno/.bun/_bun" ] && source "/Users/yumaohno/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Added by Antigravity
export PATH="/Users/yumaohno/.antigravity/antigravity/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# OpenClaw Completion
source "/Users/yumaohno/.openclaw/completions/openclaw.zsh"
