# export PATH="/opt/homebrew/bin:$PATH"
# PATH=$PATH:/Users/yumaohno/Library/Python/3.8/bin
# source ~/app/zsh-snap/znap.zsh
# source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# #znap source marlonrichert/zsh-autocomplete
# 
alias gccw='gcc -Wall -Wextra -Werror'
 alias norm='norminette -R CheckForbiddenSourceHeader'
 alias normh='norminette -R CheckDefine'
 alias gad='git add'
 alias gada='gad -A'
 alias gcm='git commit -m'
 alias gps='git push'
 alias gpl='git pull'
 alias gcl='git clone'
 alias xx='./a.out'
 alias grun='go run'
 alias gbld='go build'
 alias rmxx='rm a.out'
 alias code="open -a 'Visual Studio Code'"
 alias cddesk="cd ~/Desktop"
 alias xxrm="xx && rmxx"
 alias  ecompile='emacs --batch -f batch-byte-compile init.el'
 alias x86='arch -x86_64 zsh'
 alias mk='make'
 alias mka='make all'
 alias mkr='make re'
 alias mkc='make clean'
 alias mkfc='make fclean'
 alias mkac='make all clean'
 alias awsp="source _awsp"
# alias l='\ls'
#  alias ls='lsd'
#  alias l1='lsd -1'
#  alias la='lsd -a'
#  alias ll='lsd -l'
#  alias lt='ls --tree'
#  alias l1a='lsd -1a'
#  alias laa='lsd -1a'
#  alias la1='lsd -1a'
#  alias lla='lsd -la'
#  alias lal='lsd -la'
#  export LANG=ja_JP.UTF-8
#  setopt hist_ignore_dups
#  setopt hist_ignore_all_dups
#  setopt share_history


autoload -Uz vcs_info

autoload -Uz compinit
 compinit -u
 if [ -e /usr/local/share/zsh-completions ]; then
   fpath=(/usr/local/share/zsh-completions $fpath)
 fi
 zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
 setopt list_packed
 autoload colors
 zstyle ':completion:*' list-colors ''
 # setopt correct
 setopt no_beep

setopt prompt_subst
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' stagedstr "%F{magenta}!"
zstyle ':vcs_info:git:*' unstagedstr "%F{yellow}+"
zstyle ':vcs_info:*' formats "%F{cyan}%c%u%b%f"
zstyle ':vcs_info:*' actionformats '%b|%a'
precmd () { vcs_info }

ARCH=`uname -m`

export PATH=$PATH:~/platform-tools

# プロンプトカスタマイズ
# PROMPT='[%B%F{red}%n@%m%f%b:%F{green}%~%f]%F{cyan}$vcs_info_msg_0_%f
# [%F{cyan}${ARCH}%F{white}]%F{yellow}$%f' 
# local number_of_jobs="%(1j.%F{208} / %f%F{226}%B%j%b%f.)"
local number_of_jobs="%(1j.%F{208}/%f%F{226}%B%j%b%f.)"
PROMPT='[%B%F{green}%~%f][%F{cyan}$vcs_info_msg_0_%f]%F{yellow}${number_of_jobs}$ %f' 

export PATH="/Users/sorau/Library/Python/3.8/bin:$PATH"

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
  autoload -Uz compinit && compinit
fi


export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=$HOME/.progate/bin:$PATH

source /Users/yumaohno/.docker/init-zsh.sh || true # Added by Docker Desktop
. "$HOME/.cargo/env"
